### ISSUE TITLE
infobox renders below bank interface

### ISSUE THREAD

**Issue by 000000653** [andmcadams/weight-calculator#1]
The infobox should render above the bank interface for this plugin as the plugin is designed to always have the bank open when in use. Having your inventory at the closest possible position to the bank interface means you'll always be hiding the infobox below the bank interface when weighing things.

**Comment by andmcadams** [comment]
Fixed in 3e88ed06f4809fd2d63e7851a85f39e44f6d0f37 and will be pushed out in the next version.
